// AUTO-GENERATED by scripts/process-works.mjs
// Edit titles, roles, software, years, and youtubeId values here as needed.
// Re-running the script will preserve manual edits ONLY if you remove the
// generated outputs first; otherwise it skips already-generated assets but
// will overwrite this file. Keep your edits in source control.

export type Category = '3d' | 'directing' | 'narrative';

export type Work = {
  id: string;
  title: string;
  category: Category;
  role: string;
  software: string[];
  year: number;
  thumbnail: string;
  preview?: string;
  localVideo?: string;
  youtubeId?: string;
  gallery?: string[];
  isStatic: boolean;
};

export const works: Work[] = [
  {
    "id": "3d_product_visualization",
    "title": "3d Product Visualization",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/3d_product_visualization.jpg",
    "youtubeId": "",
    "isStatic": true
  },
  {
    "id": "flower_blooming",
    "title": "Flower Blooming",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/flower_blooming.jpg",
    "preview": "/works/previews/flower_blooming.webm",
    "localVideo": "/works/videos/flower_blooming.mp4",
    "youtubeId": "xSWOEuIaKr4",
    "isStatic": false
  },
  {
    "id": "mexico_factory",
    "title": "Mexico Factory",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/mexico_factory.jpg",
    "youtubeId": "",
    "gallery": [
      "/works/gallery/mexico_factory_01.jpg",
      "/works/gallery/mexico_factory_02.jpg",
      "/works/gallery/mexico_factory_03.jpg",
      "/works/gallery/mexico_factory_04.jpg",
      "/works/gallery/mexico_factory_05.jpg"
    ],
    "isStatic": true
  },
  {
    "id": "phone_addiction_mascot",
    "title": "Phone Addiction Mascot",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/phone_addiction_mascot.jpg",
    "youtubeId": "",
    "gallery": [
      "/works/gallery/phone_addiction_mascot_01.jpg",
      "/works/gallery/phone_addiction_mascot_02.jpg"
    ],
    "isStatic": true
  },
  {
    "id": "ruin_sentinel",
    "title": "Ruin Sentinel",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/ruin_sentinel.jpg",
    "youtubeId": "",
    "gallery": [
      "/works/gallery/ruin_sentinel_01.jpg",
      "/works/gallery/ruin_sentinel_02.jpg",
      "/works/gallery/ruin_sentinel_03.jpg",
      "/works/gallery/ruin_sentinel_04.jpg",
      "/works/gallery/ruin_sentinel_05.jpg",
      "/works/gallery/ruin_sentinel_06.jpg",
      "/works/gallery/ruin_sentinel_07.jpg",
      "/works/gallery/ruin_sentinel_08.jpg",
      "/works/gallery/ruin_sentinel_09.jpg",
      "/works/gallery/ruin_sentinel_10.jpg",
      "/works/gallery/ruin_sentinel_11.jpg",
      "/works/gallery/ruin_sentinel_12.jpg",
      "/works/gallery/ruin_sentinel_13.jpg"
    ],
    "isStatic": true
  },
  {
    "id": "sailing_to_taiwan",
    "title": "Sailing To Taiwan",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2026,
    "thumbnail": "/works/thumbs/sailing_to_taiwan.jpg",
    "preview": "/works/previews/sailing_to_taiwan.webm",
    "localVideo": "/works/videos/sailing_to_taiwan.mp4",
    "youtubeId": "JFbh9ymqGMk",
    "isStatic": false
  },
  {
    "id": "subway_wasteland",
    "title": "Subway Wasteland",
    "category": "3d",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/subway_wasteland.jpg",
    "youtubeId": "",
    "gallery": [
      "/works/gallery/subway_wasteland_01.jpg"
    ],
    "isStatic": true
  },
  {
    "id": "atlantis_promo",
    "title": "Atlantis Promo",
    "category": "directing",
    "role": "",
    "software": [],
    "year": 2026,
    "thumbnail": "/works/thumbs/atlantis_promo.jpg",
    "preview": "/works/previews/atlantis_promo.webm",
    "localVideo": "/works/videos/atlantis_promo.mp4",
    "youtubeId": "JFj2BBeVRXM",
    "isStatic": false
  },
  {
    "id": "dark_web_promo",
    "title": "Dark Web Promo",
    "category": "directing",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/dark_web_promo.jpg",
    "preview": "/works/previews/dark_web_promo.webm",
    "localVideo": "/works/videos/dark_web_promo.mp4",
    "youtubeId": "w6ygUPbjuEA",
    "isStatic": false
  },
  {
    "id": "fallen_mind",
    "title": "Fallen Mind",
    "category": "directing",
    "role": "",
    "software": [],
    "year": 2024,
    "thumbnail": "/works/thumbs/fallen_mind.jpg",
    "preview": "/works/previews/fallen_mind.webm",
    "localVideo": "/works/videos/fallen_mind.mp4",
    "youtubeId": "HlDjGAklg7g",
    "isStatic": false
  },
  {
    "id": "flipbook_mg",
    "title": "Flipbook Mg",
    "category": "directing",
    "role": "",
    "software": [],
    "year": 2024,
    "thumbnail": "/works/thumbs/flipbook_mg.jpg",
    "preview": "/works/previews/flipbook_mg.webm",
    "localVideo": "/works/videos/flipbook_mg.mp4",
    "youtubeId": "t8kY1JhJnY4",
    "isStatic": false
  },
  {
    "id": "2d_animation_colorscript",
    "title": "2d Animation Colorscript",
    "category": "narrative",
    "role": "",
    "software": [],
    "year": 2026,
    "thumbnail": "/works/thumbs/2d_animation_colorscript.jpg",
    "youtubeId": "",
    "isStatic": true
  },
  {
    "id": "small_squid_colorscript",
    "title": "Small Squid Colorscript",
    "category": "narrative",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/small_squid_colorscript.jpg",
    "youtubeId": "",
    "gallery": [
      "/works/gallery/small_squid_colorscript_01.jpg",
      "/works/gallery/small_squid_colorscript_02.jpg",
      "/works/gallery/small_squid_colorscript_03.jpg",
      "/works/gallery/small_squid_colorscript_04.jpg",
      "/works/gallery/small_squid_colorscript_05.jpg",
      "/works/gallery/small_squid_colorscript_06.jpg",
      "/works/gallery/small_squid_colorscript_07.jpg",
      "/works/gallery/small_squid_colorscript_08.jpg",
      "/works/gallery/small_squid_colorscript_09.jpg",
      "/works/gallery/small_squid_colorscript_10.jpg",
      "/works/gallery/small_squid_colorscript_11.jpg",
      "/works/gallery/small_squid_colorscript_12.jpg"
    ],
    "isStatic": true
  },
  {
    "id": "titanic_phone_storyboard",
    "title": "Titanic Phone Storyboard",
    "category": "narrative",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/titanic_phone_storyboard.jpg",
    "preview": "/works/previews/titanic_phone_storyboard.webm",
    "localVideo": "/works/videos/titanic_phone_storyboard.mp4",
    "youtubeId": "8Otn0jnXKO0",
    "isStatic": false
  },
  {
    "id": "wormhole_storyboard",
    "title": "Wormhole Storyboard",
    "category": "narrative",
    "role": "",
    "software": [],
    "year": 2025,
    "thumbnail": "/works/thumbs/wormhole_storyboard.jpg",
    "preview": "/works/previews/wormhole_storyboard.webm",
    "localVideo": "/works/videos/wormhole_storyboard.mp4",
    "youtubeId": "YT496NDWPcA",
    "isStatic": false
  }
];
